name: Run tests

on:
  push: 
   branches:
    - 'main'
  pull_request:
    branches:
     - 'main'
jobs:
  tests:
   runs-on: ubuntu-latest
#test
   steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
       node-version: 16.18
    - name: Install Dependencies
      run: |
          npm install
          npm ci
    - name: Install Docker compose
      run: npm install -g docker-compose
    - name: Automated Code Review
      run: |
          # Exécuter des outils de révision automatique du code
          # Exemple avec ESLint
          #npm install eslint
          npm run lint
      continue-on-error: false
    - name: Run tests
      run: npm test
      continue-on-error: false

    - name: Run ESLint and save report
      run: |
        npx eslint src/myApp.js --format json --output-file eslint-report.js

    - name: Upload ESLint report
      uses: actions/upload-artifact@v2
      with:
        name: eslint-report
        path: eslint-report.js

    - name: Build Docker Image
      run: |
          # Construire l'image Docker
          docker build -t myapp.
      continue-on-error: false

   #Send email  
  Send_mail_on_failure:
   runs-on: ubuntu-latest
   needs: tests
   if: failure()
   steps:
    - name: Send Email
      uses: actions/checkout@v3
      with:    
         server_address: smtp.gmail.com
         # Optional port (defaults to 465)
         server_port: 465
         username: saintpreuxjerry
         password: ${{secrets.NOTIFY_PASSWORD}}
         sender: Jerry Saint-Preux
         from: saintpreuxjerry@gmail.com
         to: djlotbo@gmail.com
         subject: Github Actions Test mail
         body: This is a test email sent from GitHub Actions.
         contentType: text/plain